### ISSUE TITLE
Does this project have a license?

### ISSUE THREAD

**Issue by ATXLtheAxolotl** [Ptkatz/SharpRakNet#1]
Does this the project have a license like MIT, ISC, etc? I would like to modify this project for my needs and implement it into another project I am working on.

**Comment by Ptkatz** [comment]
Hi, thank you for your interest in this project. 
I will add MIT license to this project later.

**Comment by ATXLtheAxolotl** [comment]
Thank you.

**Comment by ATXLtheAxolotl** [comment]
Just for your information and so you don’t think I’m just forking and abandoning. I will likely be sending many PR’s in about 13ish days, unfortunately I don’t currently have the time to work on it now as I have last minute tests and exams combined this week and the next, fun!
